repos:
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: v0.15.12
   hooks:
   - id: ruff
     args: [
       '--fix',
       '--target-version', 'py311',
       '--select', 'E,F,UP,W',
       '--ignore', 'E501',
     ]
   - id: ruff-format
     args: ['--target-version', 'py311']
